# Netlify configuration for sentientiq-marketing
# Deploy this to sentientiq.ai

[build]
  # Build command for marketing site
  command = "npm install && npm run build"
  
  # Directory to deploy
  publish = "dist"

# Environment variables
[build.environment]
  NODE_VERSION = "18"

# Custom domain
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirects for marketing site
[[redirects]]
  from = "/app"
  to = "https://sentientiq.app"
  status = 301
  force = true

[[redirects]]
  from = "/login"
  to = "https://sentientiq.app/auth"
  status = 301
  force = true

[[redirects]]
  from = "/signup"
  to = "https://sentientiq.app/auth?mode=signup"
  status = 301
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200