functionsDirectory = "/Users/matthewkiselstein/projects/sentientiq-core/netlify/functions"
functionsDirectoryOrigin = "ui"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
edge_functions = "/Users/matthewkiselstein/projects/sentientiq-core/netlify/edge-functions"
publish = "/Users/matthewkiselstein/projects/sentientiq-core/dist"
publishOrigin = "config"
commandOrigin = "ui"
command = "npm run build"
functions = "/Users/matthewkiselstein/projects/sentientiq-core/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/api/posts/*"
to = "http://3.15.29.138:8002/api/posts/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/swarm/*"
to = "http://3.15.29.138:8003/api/swarm/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/posts/*"
to = "http://3.15.29.138:8002/api/posts/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/swarm/*"
to = "http://3.15.29.138:8003/api/swarm/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]