[build]
  publish = "dist"

[[redirects]]
  from = "/api/posts/*"
  to = "http://3.15.29.138:8002/api/posts/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/swarm/*"
  to = "http://3.15.29.138:8003/api/swarm/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/stripe/webhook"
  to = "http://3.15.29.138:8005/webhook"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
