[build]
  publish = "dist"

[[redirects]]
  from = "/api/posts/*"
  to = "http://3.15.29.138:8002/api/posts/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/swarm/*"
  to = "http://3.15.29.138:8003/api/swarm/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/stripe/webhook"
  to = "http://3.15.29.138:8005/webhook"
  status = 200
  force = true

[[redirects]]
  from = "/api/evi/*"
  to = "http://3.15.29.138:8001/api/evi/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/v1/debate"
  to = "https://api.sentientiq.app/v1/boardroom"
  status = 200
  force = true
  
[[redirects]]
  from = "/api/sage/debate"
  to = "https://api.sentientiq.app/v1/boardroom"
  status = 200
  force = true
  
[[redirects]]
  from = "/api/usage/track"
  to = "https://api.sentientiq.app/v1/usage/track"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
