# SentientIQ Netlify Configuration
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  # FastAPI backend origin (update with your EC2 or Load Balancer URL)
  API_ORIGIN = "http://3.15.29.138:8001"

# Edge Functions - route /api/* to the proxy
[[edge_functions]]
  path = "/api/*"
  function = "api-proxy"

# Redirect for Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Local development configuration  
[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 3000
  publish = "dist"
  autoLaunch = false
