#!/bin/bash

echo "📋 EC2 Security Group Rules Needed:"
echo "=================================="
echo ""
echo "Inbound Rules:"
echo "  - SSH (22): Your IP"
echo "  - Custom TCP (8787): 0.0.0.0/0 (Orchestrator API)"
echo "  - Custom TCP (6379): 172.31.0.0/16 (Redis - VPC only)"
echo ""
echo "To add via AWS CLI:"
echo ""
echo "# Find your security group ID"
echo "aws ec2 describe-instances --instance-ids i-0bb996afb1cf76bab --query 'Reservations[0].Instances[0].SecurityGroups[0].GroupId' --output text"
echo ""
echo "# Add orchestrator port"
echo "aws ec2 authorize-security-group-ingress --group-id sg-YOUR-ID --protocol tcp --port 8787 --cidr 0.0.0.0/0"
echo ""
echo "Or use AWS Console: EC2 → Security Groups → Edit inbound rules"