functionsDirectory = "/Users/matthewkiselstein/projects/sentientiq-core/marketing-website/netlify/functions"
functionsDirectoryOrigin = "ui"
redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/matthewkiselstein/projects/sentientiq-core/marketing-website/dist"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/matthewkiselstein/projects/sentientiq-core/marketing-website"
command = "npm run build"
functions = "/Users/matthewkiselstein/projects/sentientiq-core/marketing-website/netlify/functions"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]